### ISSUE TITLE
Typescript support for presets?

### ISSUE THREAD

**Issue by MacroMan** [primefaces/primevue-tailwind#66] opened 2024-01-12 09:05 UTC
We have js disabled in our codebase so are unable to use a preset. 
Are there any plans to convert the presets to Typescript?

**Comment by mertsincan** [comment] 2024-01-12 16:02
Thanks a lot for your report! Nice idea, I'll talk about it with our team and decide asap.

Best Regards,

**Comment by MacroMan** [comment] 2024-01-12 17:50
We've decided to convert the Lara preset to TS ourselves as it doesn't seem like a huge effort. I'll be willing to push that back in a PR of you're interested.

**Comment by MacroMan** [comment] 2024-01-17 09:27
I have converted the Lara preset to Typescript and opened a PR here: https://github.com/primefaces/primevue-tailwind/pull/74

**Comment by mertsincan** [comment] 2024-01-17 22:04
TS-supported presets are already on our roadmap, but we have not started such work until all components' presets are written. 90% of the components are complete, I will talk to the team to highlight TS support in the roadmap. Please know that the PrimeVue and Tailwind+PrimeVue presets are under heavy development and as a team we want the design to be perfect. Therefore TS support may be delayed in several versions.

@MacroMan Thanks a lot for your PR! This will really help us.

**Comment by FalkoJoseph** [comment] 2024-01-24 23:02
> TS-supported presets are already on our roadmap, but we have not started such work until all components' presets are written. 90% of the components are complete, I will talk to the team to highlight TS support in the roadmap. Please know that the PrimeVue and Tailwind+PrimeVue presets are under heavy development and as a team we want the design to be perfect. Therefore TS support may be delayed in several versions.
> 
> @MacroMan Thanks a lot for your PR! This will really help us.

Hey just wanted to ask: if you do add TS support, will it continue to work when you're not using TS?

**Comment by MacroMan** [comment] 2024-04-03 16:12
> is there a way to get a typescript preset? i have a vue 3 typescript project but i only find the presets for javascript.

Yes, I converted the Lara preset to typescript here: https://github.com/primefaces/primevue-tailwind/pull/74

**Comment by cagataycivici** [comment] 2024-05-10 09:56
We'll work on this after v4 as pt names are updated in v4 to align with the CSS classes and design tokens.

**Comment by BryanHuntNV** [comment] 2024-07-23 21:31
Is there any update on this?

I tried hacking the Tailwind Aura presets into Typescript.  I can see the presets loaded and passed as the `pt` config parameter, but they don't appear to be applied.  Is there something fundamental I might be missing?

**Comment by goldengecko** [comment] 2024-09-17 11:26
I started some work on a typescript implementation of the Lara preset, and it was mostly working out OK, but ran into a few problems where the types were not correct/complete e.g. I remember that the menubar was missing some things from the MenubarProps.

I had other priorities so haven't pursued it at the moment, but it would really be appreciated to have a typescript version, and in the process it would help to tidy up the type definitions.

**Comment by MacroMan** [comment] 2024-09-18 10:26
@goldengecko it's probably getting a bit outdated now, but take a look at my closed PR where I already converted it for fixes: https://github.com/primefaces/primevue-tailwind/pull/74

**Comment by atakantepe** [comment] 2024-09-18 13:24
Update:
The issue is outdated due to changes in the project structure. We plan to introduce significant updates to the presets' usage to simplify the process and eliminate confusion. Along with these updates, TypeScript support will also be added. We’ve recognized the need for clearer and easier implementation, and the new structure will address these points.

For now, I’ll be closing this issue, but rest assured, TypeScript support is in our upcoming plans. Stay tuned for further updates!

**Closed by atakantepe** 2024-09-18 13:24 UTC
Labels: Status: Discussion

**Comment by msladek** [comment] 2024-10-09 17:29
@atakantepe instead of just closing the issue, can you reference any of those "significant changes" and "upcoming plans"?
