### ISSUE TITLE
FloatLabel inputs are broken with the v4 templates

### ISSUE THREAD

**Issue by dukesteen** [primefaces/primevue-tailwind#302] opened 2024-07-28 20:14 UTC
As can be seen on the official tailwind preset website, floatlabels are broken https://tailwind.primevue.org/floatlabel/ 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/4edebb63-3781-4edc-a79a-260a989fe34e">

**Comment by dukesteen** [comment] 2024-07-28 20:53
Seems like it's not happening in chrome

**Comment by dukesteen** [comment] 2024-07-29 13:50
Looks like it's a lastpass issue, as it injects itself into the input container

**Comment by dukesteen** [comment] 2024-07-29 14:27
Changing everything to `nth-child(2)` makes it work with LastPass, i'm not sure if this is the best solution.

```ts
export default {
	root: {
		class: [
			'block relative',

			// Base Label Appearance
			'[&>*:nth-child(2)]:text-surface-900/60 dark:[&>*:last-child]:text-white/60',
			'[&>*:nth-child(2)]:absolute',
			'[&>*:nth-child(2)]:top-1/2',
			'[&>*:nth-child(2)]:-translate-y-1/2',
			'[&>*:nth-child(2)]:left-3',
			'[&>*:nth-child(2)]:pointer-events-none',
			'[&>*:nth-child(2)]:transition-all',
			'[&>*:nth-child(2)]:duration-200',
			'[&>*:nth-child(2)]:ease',

			// Focus Label Appearance
			'[&>*:nth-child(2)]:has-[:focus]:-top-3',
			'[&>*:nth-child(2)]:has-[:focus]:text-sm',

			// Filled Input Label Appearance
			'[&>*:nth-child(2)]:has-[.filled]:-top-3',
			'[&>*:nth-child(2)]:has-[.filled]:text-sm'
		]
	}
}
```

**Comment by atakantepe** [comment] 2024-09-18 13:33
Hi, this issue has likely been resolved in the latest updates. I couldn't reproduce it.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.

**Closed by atakantepe** 2024-09-18 13:33 UTC
